version: '3.8'

services:
  backend:
    build: ./BackendTaskUsingGraphQL
    container_name: backend-task-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=taskdb;Username=taskuser;Password=taskpassword
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpassword
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ../task-frontend
    container_name: task-frontend
    ports:
      - "5174:80"   # Host 5174 -> container 80
    depends_on:
      - backend

volumes:
  postgres_data:
